### ISSUE TITLE
Problem importing the lib after upgrade

### ISSUE THREAD

**Issue by macelai** [odanado/aws-kms-provider#410]
Hey, thank you for this amazing lib!!

I was using on the version 0.3.4 and after upgrade it to 0.4.3. The import doesn't work anymore. Here it is the stack trace:

.../node_modules/aws-kms-provider/lib/index.js:1
export * from "./provider";
^^^^^^

SyntaxError: Unexpected token 'export'

**Comment by odanado** [comment]
@macelai 
Thank you for reporting.
Maybe, I think relate a support of ECMAScript.

What is a version of Node.js ?

**Comment by macelai** [comment]
I'm using v17.4.0

**Comment by odanado** [comment]
@macelai 
I've created a repository to see if I can reproduce the problem.
https://github.com/odan-sandbox/aws-kms-provider-syntax-error-sandbox

Running `node index.js` in this repository was successful.

Could you give me more information about the error you encountered?

- `import` or `require`
- use TypeScript?
- value of `type` field in `package.json`
- etc

**Comment by macelai** [comment]
@odanado 

- using `import` -> `import { KmsProvider } from 'aws-kms-provider'`
- No typescript
- "type": "module",

Here is my package.json

{
  "name": "edge-of-nft-be",
  "version": "1.0.0",
  "dependencies": {
    "aws-kms-provider": "^0.3.4",
    "aws-sdk": "^2.1071.0",
    "axios": "0.25.0",
    "bcrypt": "5.0.1",
    "body-parser": "1.19.1",
    "compression": "1.7.4",
    "consign": "0.1.6",
    "cors": "2.8.5",
    "dotenv": "16.0.0",
    "express": "4.17.2",
    "express-rate-limit": "6.2.0",
    "jsonwebtoken": "8.5.1",
    "mongoose": "6.2.0",
    "validatorjs": "3.22.1",
    "web3": "^1.7.0"
  },
  "main": "app.js",
  "type": "module",
  "directories": {
    "lib": "lib"
  },
  "engines": {
    "node": "17.0.0"
  },
  "scripts": {
    "start": "nodemon --experimental-json-modules app.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "prepare": "husky install"
  },
  "author": "Vinicius Macelai",
  "license": "ISC",
  "devDependencies": {
    "husky": "^7.0.4",
    "lint-staged": "^12.3.3",
    "nodemon": "^2.0.15",
    "prettier": "^2.5.1"
  },
  "lint-staged": {
    "*.{js,css,md}": "prettier --write"
  }
}

**Comment by macelai** [comment]
I confirm it's solved, thank you
